---

- name: Cisco Banner Changer
  hosts: all
  gather_facts: false

  tasks:
  - name: Configure the login banner using delimiter
    cisco.ios.ios_banner:
      banner: motd
      multiline_delimiter: #
      text: --------------------
            -----DATEC LAB------
            -----.Welcome.------
            --------------------
      state: present
