---

- name: Cisco show ip int bri example
  hosts: all
  gather_facts: false

  tasks:
    - name: run show ip int bri on the routers
      ios_command:
        commands: terminal length 0
        commands: show ip int bri
      register: output

    - name: print output
      debug:
        var: output.stdout_lines
