---
- hosts: all

  tasks:
   - name: show ip int
     ios_command:
       commands:
         - show ip int bri   
     register: config

   - name: save output to /etc/ansible/backups 
     copy: 
       content: "{{ config.stdout[0] }}"
       dest: "/etc/ansible/backups/show_run_{{ inventory_hostname }}.txt"

 

